---
google:
        fonts: 'Roboto:400,700'
        #        analytics: UA-39520577-1
future: true
timezone: UTC
title: 21Cromosomi
description: 21Cromosomi
url: https://21cromosomi.5p2p.it
baseurl: ''
permalink: "/:title/"
exclude: [.git]
collections:
        pages:
                output: true
defaults:
        - scope:
                path: ""
          values:
                layout: post
