---
google:
        fonts: 'Roboto:400,700'
        #        analytics: UA-39520577-1
future: true
timezone: UTC
title: Cromosoma21
subtitle: Cromosoma21
description: Cromosoma21
url: https://cromosoma21.5p2p.it
baseurl: ''
permalink: "/:title/"
exclude: [.git]
collections:
        pages:
                output: true
defaults:
        - scope:
                path: ""
          values:
                layout: post
